Adjust `Code` to match the actual browsers
pyfisch/keyboard-types pull request #15
Opened 2021-10-05 15:20 UTC by CryZe

This adds the missing `F13` - `F24` values, adds aliases for various values that are still used in Firefox and Safari and adds some values that are only used by Chromium.

Resolves #12, #13, #14

2021-10-18 18:37 UTC, pyfisch commented
Hi @CryZe I'll review the code shortly. Thanks for your patience.

2021-11-07 20:26 UTC, pyfisch requested changes
Extending to F13-F24 is good. The alternatives are useful to interact with browsers and shouldn't cause problems.

2021-11-07 20:26 UTC, pyfisch commented on convert.py
> +    for chromium_only in [
can you put this list in a separate variable `chromium_key_codes`? Multi-line loop conditions are a bit uncommon.

2021-11-07 20:26 UTC, pyfisch commented on convert.py
> +    with open('src/key.rs', 'w', encoding='utf-8') as output:
good catch

2021-11-07 20:27 UTC, pyfisch commented on src/code.rs
> +            F24 => f.write_str("F24"),
For consistence can you add F13 to F24 to Key as well?

2021-11-14 19:35 UTC, CryZe commented
I addresses the review comments and also fixed the regex. Apparently they published new versions of both specs and added a new `Required` column that the regex couldn't handle.

2021-11-17 11:53 UTC, merged

2021-11-17 11:59 UTC, CryZe commented
Thank you. Can you potentially release a 0.6.2 for this? I'd like to integrate these changes into druid which has a lot of TODOs regarding missing keycodes.

2021-11-17 12:03 UTC, pyfisch commented
Yes, already done. :smile: