Separate `Key` into `Character` and `NamedKey`
pyfisch/keyboard-types pull request #50
Opened 2024-12-01 15:41 UTC by madsmtm

This makes most of the key `Copy`, and allows other crates like Winit to more easily use their own string types.

See https://github.com/rust-windowing/winit/issues/2995 and https://github.com/rust-windowing/winit/pull/3143 for discussion on a similar change in Winit.

Part of https://github.com/pyfisch/keyboard-types/issues/19.

2024-12-22 13:30 UTC, pyfisch commented
Please rebase the PR.

I wonder if it is possible to have a `Key<T=String>` which implements `Copy` if T is `Copy` as well? I don't really like having separate types for keys and named keys.

2025-02-13 19:03 UTC, madsmtm commented
> I don't really like having separate types for keys and named keys.

My main argument here is that `Character` is not in spec, and that even [the `key` attribute in the spec](https://www.w3.org/TR/uievents-key/#key-attr-values) is split into two categories, namely "key string" and "named key".

There's also a question about normalization; technically `Key` can currently contain a lot of invalid/unexpected states, such as `Key::Character("Shift")` or `Key::Character("\t")`, by explicitly splitting it up into `Key` and `NamedKey`, we alleviate some of those concerns.

> I wonder if it is possible to have a `Key<T=String>` which implements `Copy` if T is `Copy` as well?

Would definitely be technically possible, but wouldn't really help Winit which also wants extra variants, such as [`Dead`](https://docs.rs/winit/0.30.9/winit/keyboard/enum.Key.html#variant.Dead) and [`Native`](https://docs.rs/winit/0.30.9/winit/keyboard/enum.Key.html#variant.Unidentified).

2025-03-23 10:45 UTC, pyfisch requested changes
Looks good. I will merge it with the nit addressed.

2025-03-23 10:45 UTC, pyfisch commented on src/lib.rs
> +            Self::Named(k) => write!(f, "{k}"),
Avoid `write!` and use `write_str` and `fmt` directly.

2025-03-23 11:17 UTC, madsmtm commented
Done!

2025-03-23 11:21 UTC, pyfisch commented
@madsmtm The docs need to used named key.

```
74 | ...es to the phone’s main screen), use [`GoHome`][Key::GoHome].
   |                                                   ^^^^^^^^^^^ no item named `Key` in scope
```

2025-03-23 11:32 UTC, pyfisch approved these changes

2025-03-23 11:32 UTC, merged